package com.pojo;
// Generated Oct 25, 2020 3:10:10 PM by Hibernate Tools 4.3.1

import com.dao.AdminDAO;
import java.util.List;
import javax.faces.bean.ManagedBean;




/**
 * Admin generated by hbm2java
 */
@ManagedBean
public class Admin  implements java.io.Serializable {


     private Integer id;
     private String username;
     private String password;

    public Admin() {
    }

    public Admin(String username, String password) {
       this.username = username;
       this.password = password;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

     public String login(){
        AdminDAO admin = new AdminDAO();
        List<Admin> adm = admin.alogin(username, password);
        
        try{
            if(adm != null){
            username = adm.get(0).username;
            password = adm.get(0).password;
            return "transaction";
            }
        } catch (Exception e) {
            System.out.println(e);
        }
        return "gagal";
    }


}


