package com.pojo;
// Generated Oct 25, 2020 3:10:10 PM by Hibernate Tools 4.3.1

import com.dao.PartyDAO;
import java.util.ArrayList;
import java.util.List;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;




/**
 * Party generated by hbm2java
 */
@ManagedBean
public class Party  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String address;
     private String city;
     private int zip;
     private String contact;
     private String note;
     private String role;

    public Party() {
    }

    public Party(String name, String address, String city, int zip, String contact, String note, String role) {
       this.name = name;
       this.address = address;
       this.city = city;
       this.zip = zip;
       this.contact = contact;
       this.note = note;
       this.role = role;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public int getZip() {
        return this.zip;
    }
    
    public void setZip(int zip) {
        this.zip = zip;
    }
    public String getContact() {
        return this.contact;
    }
    
    public void setContact(String contact) {
        this.contact = contact;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }

    public List<Party> getAllRecords(){
        List<Party> pList = new ArrayList<Party>();
        PartyDAO party = new PartyDAO();
        pList = party.getAll();
        return pList;
    }
    
    public String add(){
        PartyDAO add = new PartyDAO();
        add.add(this);
        return "party";
    }
    
    public void getById(){
        PartyDAO party = new PartyDAO();
        List<Party> pList = party.getById(id);
        name = pList.get(0).name;
        address = pList.get(0).address;
        city = pList.get(0).city;
        zip = pList.get(0).zip;
        contact = pList.get(0).contact;
        note = pList.get(0).note;
        role = pList.get(0).role;
    }
    
    public String getPartyName(Integer id){
        PartyDAO party = new PartyDAO();
        List<Party> pList = party.getById(id);
        name = pList.get(0).name;
        return name;
    }
    
    public String edit(){
        PartyDAO party = new PartyDAO();
        party.edit(this);
        name = "";
        address = "";
        city = "";
        zip = zip;
        contact = "";
        note = "";
        note = "";
        FacesMessage facesMessages = new FacesMessage(FacesMessage.SEVERITY_INFO,"Berhasil Edit Data",null);
        return "party";
    }
    
    public String delete(){
        PartyDAO party = new PartyDAO();
        party.delete(id);
        name = "";
        address = "";
        city = "";
        zip = zip;
        contact = "";
        note = "";
        note = "";
        return "party";
    }
    
    public String home(){
        return "party";
    }
    
    public String crud(){
        return "party_crud";
    }


}


