package com.pojo;
// Generated Oct 25, 2020 3:10:10 PM by Hibernate Tools 4.3.1

import com.dao.ProductsDAO;
import java.util.ArrayList;
import java.util.List;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;




/**
 * Products generated by hbm2java
 */
@ManagedBean
public class Products  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String size;
     private String label;
     private String type;
     private int stock;
     private int received;
     private int shipped;
     private String note;

    public Products() {
    }

    public Products(String name, String size, String label, String type, int stock, int received, int shipped, String note) {
       this.name = name;
       this.size = size;
       this.label = label;
       this.type = type;
       this.stock = stock;
       this.received = received;
       this.shipped = shipped;
       this.note = note;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getSize() {
        return this.size;
    }
    
    public void setSize(String size) {
        this.size = size;
    }
    public String getLabel() {
        return this.label;
    }
    
    public void setLabel(String label) {
        this.label = label;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public int getStock() {
        return this.stock;
    }
    
    public void setStock(int stock) {
        this.stock = stock;
    }
    public int getReceived() {
        return this.received;
    }
    
    public void setReceived(int received) {
        this.received = received;
    }
    public int getShipped() {
        return this.shipped;
    }
    
    public void setShipped(int shipped) {
        this.shipped = shipped;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }

    public List<Products> getAllRecords(){
        List<Products> prodList = new ArrayList<Products>();
        ProductsDAO product = new ProductsDAO();
        prodList = product.getAll();
        return prodList;
    }
    
    public String add(){
        ProductsDAO add = new ProductsDAO();
        add.add(this);
        return "product";
    }
    
    public void getById(){
        ProductsDAO product = new ProductsDAO();
        List<Products> productList = product.getById(id);
        name = productList.get(0).name;
        size = productList.get(0).size;
        label = productList.get(0).label;
        type = productList.get(0).type;
        stock = productList.get(0).stock;
        received = productList.get(0).received;
        shipped = productList.get(0).shipped;
        note = productList.get(0).note;
    }
    
    public String getProductName(Integer id){
        ProductsDAO product = new ProductsDAO();
        List<Products> productList = product.getById(id);
        name = productList.get(0).name;
        return name;
    }
    
    public String edit(){
        ProductsDAO product = new ProductsDAO();
        product.edit(this);
        name = "";
        size = "";
        label = "";
        type = "";
        stock = stock;
        received = received;
        shipped = shipped;
        note = "";
        FacesMessage facesMessages = new FacesMessage(FacesMessage.SEVERITY_INFO,"Berhasil Edit Data",null);
        return "product";
    }
    
    public String delete(){
        ProductsDAO product = new ProductsDAO();
        product.delete(id);
        name = "";
        size = "";
        label = "";
        type = "";
        stock = stock;
        received = received;
        shipped = shipped;
        note = "";
        return "product";
    }
    
    public String home(){
        return "product";
    }
    
    public String crud(){
        return "product_crud";
    }


}


