package com.pojo;
// Generated Oct 25, 2020 3:10:10 PM by Hibernate Tools 4.3.1

import com.dao.TransDAO;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.faces.bean.ManagedBean;

/**
 * Trans generated by hbm2java
 */
@ManagedBean
public class Trans  implements java.io.Serializable {


     private Integer id;
     private int partyId;
     private int productId;
     private int amount;
     private Date date;
     private String type;

    public Trans() {
    }

    public Trans(int partyId, int productId, int amount, Date date, String type) {
       this.partyId = partyId;
       this.productId = productId;
       this.amount = amount;
       this.date = date;
       this.type = type;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getPartyId() {
        return this.partyId;
    }
    
    public void setPartyId(int partyId) {
        this.partyId = partyId;
    }
    public int getProductId() {
        return this.productId;
    }
    
    public void setProductId(int productId) {
        this.productId = productId;
    }
    public int getAmount() {
        return this.amount;
    }
    
    public void setAmount(int amount) {
        this.amount = amount;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    public List<Trans> getAllRecords(){
        List<Trans> tList = new ArrayList<Trans>();
        TransDAO t = new TransDAO();
        tList = t.getAll();
        return tList;
    }
    
    public String add(){
        TransDAO add = new TransDAO();
        add.add(this);
        return "transaction";
    }
    
    public void getById(){
        TransDAO t = new TransDAO();
        List<Trans> tList = t.getById(id);
        partyId = tList.get(0).partyId;
        productId = tList.get(0).productId;
        amount = tList.get(0).amount;
        date = tList.get(0).date;
        type = tList.get(0).type;
    }
    
    public String home(){
        return "transaction";
    }
    
    public String crud(){
        return "transaction_crud";
    }


}


